apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: gophish-backend-config
  namespace: gophish
spec:
  healthCheck:
    timeoutSec: 1
    type: HTTPS
    requestPath: /login
    port: 3333

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: gophish-http-backend-config
  namespace: gophish
spec:
  healthCheck:
    timeoutSec: 1
    type: HTTPS
    requestPath: /robots.txt
    port: 8443
